version: 2.1

# resuable job code like functions in python
# resuable job code like functions in python
commands:
  print_pipeline_id:
    description: "A very simple command for printing pipeline id"
    parameters:
      id:
        type: string
        default: "1234567890" 
    steps:
      - run: echo << parameters.id >>

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello world and save the output"
          command: echo "Hello, world!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Print hello world output"
          command: cat ~/output.txt
  
  print_id_from_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id:
          id: << pipeline.id >>

  print_var:
    docker:
      - image: cimg/base:2021.11
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_NAME
            echo $AWS_DEFAULT_REGION	
            
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit fix

workflows:
  my_workflow:
    jobs:
      - print_hello
      - print_output_file:
          requires: [print_hello]
      - print_var
      - print_id_from_command
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
