version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  create_ansible_inventory:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run: touch inventory
      - run: echo "[all]" > inventory
      - run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory
      - save_cache:
          key: "ansible-inventory"
          paths:
            - ./
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
            - "ansible-inventory"
      - run: npm i
      - run: npm run test
      - run: cat inventory

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit fix

workflows:
  my_workflow:
    jobs:
      - build
      - create_ansible_inventory
      - test:
          requires:
            - build
            - create_ansible_inventory
      - analyze:
          requires:
            - test
